export const TODO = {
  ADD: 'ADD_TODO',
  TOGGLE: 'TOGGLE_TODO',
  DELETE: 'DELETE_TODO'
}

export const FILTER = {
  SET: 'SET_VISIBILITY_FILTER',
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}

export const API = {
  LOAD_TODOS: 'API_LOAD_TODOS',
  FETCH_TODOS: 'API_FETCH_TODOS',
  RESOLVE_TODOS: 'API_RESOLVE_TODOS'
}
